##########################################################
#                                                        #
#                  Solar Neutrino Generator Example      #
#                                                        #
##########################################################
#/bx/physics/optical 0
/bx/detector/nopmts true 
/bx/physics/decay      1
/bx/physics/hadronic standard

#/bx/physics/new_em 1
/bx/physics/nuclear 1
/run/writeisotopes 1

#PreInit:

#  Define the level of verbosity of messages
# options: development debugging, trace, routine, warning, error
# default: routine
#/bxlog trace 

#Run number being simulated
/bx/detector/run_number 12106

#Detector configuration. Possible choices are: full, fullWater, inWater, inScint, outer, ctf
#Default: full
/bx/detector/configuration full

#PMTs distribution. Possible choices are: real, uniform.
#Default: real
/bx/detector/PMTdistribution real
#Number of PMTs defined only for uniform distribution
#/bx/detector/PMTnumber 2000

#PMT configuration. Possible choices are: diskPMT, diskPMTwithConcentrator, simplePMT
#default: simplePMT
/bx/detector/PMTconfiguration simplePMT

#Setting of NoConcentrators (true=concentrators disabled for any PMT configuration):
/bx/detector/noConcentrators false

#Vessel's configuration
/bx/detector/deformed_vessel true
/bx/detector/vessel_step 1 cm

#Geometry debugging
/bx/detector/check_overlaps false



# Set the event report frequency
# default: 1000
/event/eventreport  1
#/event/verbosity  1

/event/npethreshold -1

# Define output file name

/run/filename AmBe

# Define  random seed
/run/heprandomseed 12345679

#/bx/detector/source/type Am-Be

# Attention - the source position should be printed in the macro twice - once for container here !!!!!! 
# second time below for the Am-Be generator 
#/bx/detector/source/origin 0. 0. 0.0 mm


#-----------------------------------
/run/initialize
#-----------------------------------
/bx/stack/select Neutron
/bx/generator/select AmBe

/bx/generator/AmBe/source all
# all neutron0G neutron1G neutron2G- you can choose


# Attention - the source position should be printed in the macro twice - once for container !!!!!!
# second time here for the Am-Be generator 
/bx/generator/AmBe/sphere_origin 0 0 0.0 mm

/bx/generator/AmBe/sphere_radius 0.01 cm


/run/beamOn 10 

