##########################################################
#                                                        #
#                  Solar Neutrino Generator Example      #
#                                                        #
##########################################################
/bx/physics/optical 1
/bx/physics/hadronic standard
/bx/physics/decay 1


#PreInit:

#  Define the level of verbosity of messages
# options: development debugging, trace, routine, warning, error
# default: routine
/bxlog routine

# Define output file name
#/run/filename gunoutput

# Define  random seed
#/run/heprandomseed 12345679

#Run number being simulated
/bx/detector/run_number 11100

#Detector configuration. Possible choices are: full, fullWater, inWater, inScint, outer, ctf
#Default: full
/bx/detector/configuration full

#PMTs distribution. Possible choices are: real, uniform.
#Default: real
/bx/detector/PMTdistribution real
#Number of PMTs defined only for uniform distribution
#/bx/detector/PMTnumber 2000

#PMT configuration. Possible choices are: diskPMT, diskPMTwithConcentrator, simplePMT
#default: simplePMT
/bx/detector/PMTconfiguration simplePMT

#Setting of NoConcentrators (true=concentrators disabled for any PMT configuration):
/bx/detector/noConcentrators false

#Vessel's configuration
/bx/detector/deformed_vessel true
/bx/detector/vessel_step 1 cm

#Geometry debugging
/bx/detector/check_overlaps false


/event/npethreshold 0

# Define output file name

/run/filename Geo2Surf.mac

# Define  random seed
/run/heprandomseed 12345679


#-----------------------------------
/run/initialize
#-----------------------------------

/bx/stack/select Neutron
/bx/generator/select AntiNu
/bx/generator/AntiNu/source Geo

# Geo Reactor GeoPositron ReactorPositron neutron U Th Sun Flat - you can choose 9 possibilities


/bx/generator/AntiNu/surface_radius 4.00 m


/run/beamOn 10000
