##########################################################
#                                                        #
#                  Li9He8  Generator Example             #
#                                                        #
##########################################################
#PreInit:

#  Define the level of verbosity of messages
# options: development debugging, trace, routine, warning, error
# default: routine
/bxlog routine 


# Set the event report frequency
# default: 1000
/event/eventreport  1
/event/verbosity  1

/event/npethreshold 0

# Define output file name

/run/filename LiHe

# Define  random seed
/run/heprandomseed 234566

#Run number being simulated
/bx/detector/run_number 12106

#Detector configuration. Possible choices are: full, fullWater, inWater, inScint, outer, ctf
#Default: full
/bx/detector/configuration full

#PMTs distribution. Possible choices are: real, uniform.
#Default: real
/bx/detector/PMTdistribution real
#Number of PMTs defined only for uniform distribution
#/bx/detector/PMTnumber 2000

#PMT configuration. Possible choices are: diskPMT, diskPMTwithConcentrator, simplePMT
#default: simplePMT
/bx/detector/PMTconfiguration simplePMT

#Setting of NoConcentrators (true=concentrators disabled for any PMT configuration):
/bx/detector/noConcentrators false

#Vessel's configuration
/bx/detector/deformed_vessel true
/bx/detector/vessel_step 1 cm

#Geometry debugging
/bx/detector/check_overlaps false

#/bx/physics/optical 0
/bx/physics/hadronic standard
/bx/physics/decay 1
#/bx/detector/nopmts true


#-----------------------------------
/run/initialize
#-----------------------------------

/bx/stack/select Neutron
/bx/generator/select Li9He8
/bx/generator/Li9He8/source Li9
#you can choose between He8 and Li9


/bx/generator/Li9He8/sphere_radius 4 cm


/run/beamOn 20 
