##########################################################
#                                                        #
#                  Solar Neutrino Generator Example      #
#                                                        #
##########################################################
#/bx/physics/optical 0
#/bx/detector/nopmts true 
/bx/physics/decay      1
/bx/physics/hadronic standard

#/bx/physics/new_em 1
/bx/physics/nuclear 1
/run/writeisotopes 1

#PreInit:

#  Define the level of verbosity of messages
# options: development debugging, trace, routine, warning, error
# default: routine
/bxlog trace 

#Run number being simulated
/bx/detector/run_number 12106

#Detector configuration. Possible choices are: full, fullWater, inWater, inScint, outer, ctf
#Default: full
/bx/detector/configuration full

#PMTs distribution. Possible choices are: real, uniform.
#Default: real
/bx/detector/PMTdistribution real
#Number of PMTs defined only for uniform distribution
#/bx/detector/PMTnumber 2000

#PMT configuration. Possible choices are: diskPMT, diskPMTwithConcentrator, simplePMT
#default: simplePMT
/bx/detector/PMTconfiguration simplePMT

#Setting of NoConcentrators (true=concentrators disabled for any PMT configuration):
/bx/detector/noConcentrators false

#Vessel's configuration
/bx/detector/deformed_vessel true
/bx/detector/vessel_step 1 cm

#Geometry debugging
/bx/detector/check_overlaps false



# Set the event report frequency
# default: 1000
/event/eventreport  1
#/event/verbosity  1

/event/npethreshold -1

# Define output file name

/run/filename AmBe

# Define  random seed
/run/heprandomseed 12345679

#/bx/detector/source/type Am-Be

# Attention - the source position should be printed in the macro twice - once for container here !!!!!! 
# second time below for the Am-Be generator 
#/bx/detector/source/origin 0. 0. 0.0 mm


#-----------------------------------
/run/initialize
#-----------------------------------
/bx/stack/select Neutron
/bx/generator/select AmBe

/bx/generator/AmBe/source all
# all neutron0G neutron1G neutron2G- you can choose


# Attention - the source position should be printed in the macro twice - once for container !!!!!!
# second time here for the Am-Be generator 
/bx/generator/AmBe/sphere_origin 0 0 0.0 mm

/bx/generator/AmBe/sphere_radius 0.01 cm


# Macro file for the visualization setting in the initialization phase 
# of the B1 example when running in interactive mode
#

# Use these open statements to open selected visualization
#
# Use this open statement to create an OpenGL view:
#/vis/open OGL 600x600-0+0
#
# Use this open statement to create an OpenInventor view:
#/vis/open OI
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:


/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointVector 1 0.5 0.5
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/lightsVector -1 0 0
#
# Specify style (surface, wireframe, auxiliary edges,...)
#/vis/viewer/set/style wireframe
#/vis/viewer/set/auxiliaryEdge true
#/vis/viewer/set/lineSegmentsPerCircle 100
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
# To select or override default colours (note: e+ is blue by default):
#/vis/modeling/trajectories/list
#/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow
#
# To superimpose all of the events from a given run:
#/vis/scene/endOfEventAction accumulate
#
# Decorations
# Name
/vis/set/textColour green
/vis/set/textLayout right
#/vis/scene/add/text2D 0.9 -.9 24 ! ! Borexino Montecarlo by Alessio e Simone
# or, if your system does not support right-adjustment
#/vis/scene/add/text2D 0 -.9 24 ! ! exampleB1
/vis/set/textLayout    # Revert to normal (left adjusted) layout
/vis/set/textColour    # Revert to default text colour (blue)
#
# Axes, scale, etc.
#/vis/scene/add/scale   # Simple scale line
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
#/vis/scene/add/date    # Date stamp
#/vis/scene/add/logo2D  # Simple logo
#/vis/scene/add/logo    # 3D logo
#
# Frame
/vis/set/colour red
/vis/set/lineWidth 2
/vis/scene/add/frame   # Simple frame around the view
/vis/set/colour        # Revert to default colour (white)
/vis/set/lineWidth     # Revert to default line width (1.)
#
# Attach text to one edge of Shape1, with a small, fixed offset
#/vis/scene/add/text 0 6 -4 cm 18 4 4 Shape1
# Attach text to one corner of Shape2, with a small, fixed offset
#/vis/scene/add/text 6 7 10 cm 18 4 4 Shape2
#
# To get nice view
#/vis/geometry/set/visibility World 0 false
#/vis/geometry/set/visibility Envelope 0 false
#/vis/viewer/set/style surface
#/vis/viewer/set/hiddenMarker true
#/vis/viewer/set/viewpointThetaPhi 120 150
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush


/run/beamOn 10 

